# Agent configuration
COORDINATOR_AGENT_MODEL: gpt-5-nano
AGENT_MAX_HISTORY: 10
AGENT_TEMPERATURE: 0.01
DEFAULT_MAX_DOCUMENTS: 5

RESERVATION_AGENT_MODEL: gpt-5-nano
RESERVATION_AGENT_TEMPERATURE: 0.01


# Retrieval configuration
RETRIEVAL_API_ENDPOINT: http://olama:11434
RETRIEVAL_MODEL: llama3.2
RETRIEVAL_TOP_K: 5

# Database configuration
DATABASE_DRIVER: postgresql
DATABASE_PORT: 5432